In [1]:
pwd

'C:\\Users\\Public'

In [4]:
import numpy
n=numpy.arange(27)
n


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
m=numpy.asarray([[12,133,15,19],[],[]])
m

array([list([12, 133, 15, 19]), list([]), list([])], dtype=object)

In [9]:
print(m)

[list([12, 133, 15, 19]) list([]) list([])]


In [3]:
import cv2

In [4]:
image=cv2.imread("C:/Users/Balu/Downloads/imgl.png",0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
image=cv2.imread("C:/Users/Balu/Downloads/imgl.png",1)
image

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [6]:
image=cv2.imread("C:/Users/Balu/Downloads/imgl.png",1)
print(image)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [8]:
cv2.imwrite("new.png",image)

True

In [10]:
image1=cv2.imread("C:/Users/Balu/Downloads/imgl.png",0)
image1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [14]:
image1[1:3]

array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
image1[1:3,2:4]

array([[255, 255],
       [255,  97]], dtype=uint8)

In [17]:
for b in image1:
    print(b)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [18]:
for b in image1.T:
    print(b)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [20]:
for k in image1.flat:
    print(k)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [24]:
import numpy
horizontaladd=numpy.hstack((image1,image1))
horizontaladd

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
Veradd=numpy.vstack((image1,image1))
Veradd

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
horizontaladd=numpy.hstack((image1,image1))
print(horizontaladd)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [28]:
hsplit=numpy.hsplit(image1,3)
hsplit

ValueError: array split does not result in an equal division

In [29]:
hsplit=numpy.hsplit(image1,5)
hsplit

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [35]:
vsplit=numpy.vsplit(image1,3)
vsplit

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]